plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.2-SNAPSHOT'
}

group = project.property('group')
version = project.property('version')
base.archivesBaseName = project.property('modid')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

sourceSets {
    a126 {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
    b173 {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.wagyourtail.xyz/releases' }

    ivy {
        // We need this because the b1.7.3 forge dependency doesn't have metadata
        url 'https://maven.wagyourtail.xyz/releases'

        patternLayout {
            artifact('[organisation]/[module]/[revision]/[module]-[revision]-[classifier].zip')
            m2compatible = true
        }
        metadataSources {
            artifact()
        }
    }
}

unimined {
    useGlobalCache = false

    minecraft(sourceSets.b173) {
        version 'b1.7.3'
        side 'client'

        mappings {
            retroMCP("b1.7")

            stubs(['official', 'retroMCP']) {
                def base = 'net/minecraft/src'
                def mapClass = { name ->
                    def path = "$base/$name"
                    c(name, path, path)
                }

                // Modloader
                ['BaseMod', 'EntityRendererProxy', 'MLProp', 'ModLoader', 'ModTextureAnimation', 'ModTextureStatic'].each(mapClass)

                // ModloaderMP
                ['BaseModMp', 'ISpawnable', 'ModLoaderMp', 'NetClientHandlerEntity', 'Packet230ModLoader'].each(mapClass)

                // Forge
                ['ArmorProperties', 'BlockTextureParticles', 'Configuration', 'ForgeHooks', 'ForgeHooksClient', 'IArmorTextureProvider', 'IBlockSecondaryProperties', 'IBucketHandler', 'IConnectRedstone', 'ICraftingHandler', 'ICustomItemRenderer', 'IDestroyToolHandler', 'IHighlightHandler', 'IMultipassRender', 'IOverrideReplace', 'ISleepHandler', 'ISpecialArmor', 'ISpecialResistance', 'ITextureProvider', 'IUseItemFirst', 'MinecraftForge', 'MinecraftForgeClient', 'Property'].collect { "forge/$it" }.each(mapClass)
            }
        }

        jarMod {
            transforms "${modid}.transform"
        }

        runs {
            config('client') {
                jvmArgs '-Djma.debug=true'
            }
        }
    }

    minecraft(sourceSets.a126) {
        version 'a1.2.6'
        side 'client'

        mappings {
            retroMCP("a1.2.6")

            stubs(['official', 'retroMCP']) {
            }
        }

        jarMod {
            transforms "${modid}.transform"
        }

        runs {
            config('client') {
                jvmArgs '-Djma.debug=true'
            }
        }
    }
}

dependencies {
    b173JarMod 'risugami:modloader:b1.7.3'
    b173JarMod fileTree(dir: 'jarmods', include: ['*.jar', '*.zip'])
}

b173Jar() {

    manifest {
        attributes(
            'JarModAgent-Transforms': "${modid}.transform",
            'JarModAgent-Refmaps': "${modid}-refmap.json"
        )
    }
}

a126Jar() {

    manifest {
        attributes(
                'JarModAgent-Transforms': "${modid}.transform",
                'JarModAgent-Refmaps': "${modid}-refmap.json"
        )
    }
}
